language: node_js
node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/weyithara_thesiti

before_script:
  - psql -c 'create database  weyithara_thesiti;' -U postgres
  - psql -U postgres -d weyithara_thesiti -a -f wwaiters.test.sql

services:
  - postgresql
