language: node_js
node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/malthi

before_script:
  - psql -c 'create database  malthi;' -U postgres
  - psql -U postgres -d malthi -a -f multi.sql

services:
  - postgresql